"""create users table

Revision ID: 43e02bd946d9
Revises: 
Create Date: 2026-06-17 12:20:18.430100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e02bd946d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('PAYABLE', 'RECEIVABLE', name='kind'), nullable=False),
    sa.Column('issued', sa.Date(), nullable=False),
    sa.Column('due', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'PENDING', 'OVERDUE', 'PARTIAL', name='status'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('futures')
    # ### end Alembic commands ###
