"""add recurrence to futures

Revision ID: f65aeba13955
Revises: 43e02bd946d9
Create Date: 2026-06-17 19:56:00.457709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65aeba13955'
down_revision: Union[str, Sequence[str], None] = '43e02bd946d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('futures', sa.Column('recurrence', sa.Enum('ONCE', 'WEEKLY', 'MONTHLY', 'INSTALLMENTS', name='recurrence'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('futures', 'recurrence')
    # ### end Alembic commands ###
